### PR TITLE
Remove pyreadline as it causes errors in nxcdb

### LINKED ISSUE #170: Windows install error
To deploy via poetry on Windows, you need to install rust and also change pyreadline to pyreadline3. Please update dependencies and instructions!

### PR DESCRIPTION
**Pull request by NeffIsBack**
Fixes #170 and errors pointed out on discord. Pyreadline is probably not used by impacket anyway.

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
Did you test the build to check? Because when I was making the builder it was throwing an error without it.

**Comment by NeffIsBack** [comment]
I did, but didn't get an error. Can you revalidate tho, if you still get one?

**Comment by Marshall-Hallenbeck** [comment]
Building locally now on my Win11 machine

**Comment by Marshall-Hallenbeck** [comment]
It builds successfully but running it throws import errors:

image

I'll sort through them.

**Comment by Marshall-Hallenbeck** [comment]
Installed dependencies via `poetry install` then ran pyinstaller to build via `pyinstaller netexec.spec` and then ran the binary it created (dist/nxc.exe) and it worked.

**Review by Marshall-Hallenbeck — APPROVED** [review]

**Pull request merged**
