### PR TITLE
add argcomplete bash/zsh completion

### PR DESCRIPTION
**Pull request by Adamkadaban**
Needed to move `len(sys.argv) == 1` check after parsing args to make sure autocomplete can run the program correctly

Users can get completion by running `eval "$(register-python-argcomplete nxc)"` if they want tab completion
	This is something that I can add to the wiki if the PR gets approved

### CODE REVIEW

**Comment by NeffIsBack** [comment]
I really like it! I also fixed the completion for modules, so you also can tab-to-complete them as well. Gonna push the fixes now
image

**Comment by Adamkadaban** [comment]
@NeffIsBack Nice! Thanks for the help

**Comment by NeffIsBack** [comment]
`register-python-argcomplete nxc >> ~/.zshrc` 
This will register the argcomplete permanently in kali

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Comment by NeffIsBack** [comment]
If you have the time it would be nice if you PR the setup guide to the wiki :)

**Pull request merged**
