### PR TITLE
Fix bug in WCC module

### PR DESCRIPTION
**Pull request by fpreynaud**
Fixes bug introduced by commit bfd32f19103c4b069f93cb07c7f273d911be40bc

It was causing errors like the following saying that the variable 'data' did not exist:
image

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Thanks for the bug report!
Can you show the working example? It's really odd to me, from my understanding `_data` should not be defined in the scope of the `return` in the first place.

**Comment by fpreynaud** [comment]
Sure, here's the working example:
image

What happens is (schematically)
```python
if (condition):
    data = value # data gets defined here
else:
    for _, _, data in subkey_values(): # data gets defined here again
        # do stuff
return data
````
If the 'data' in the for is replaced with '_data', then when in the else statement 'data' is never defined, so the function fails to return it

**Comment by NeffIsBack** [comment]
Thanks!
Hmm that was my idea as well, but if we don't run the first if=true block `data` shouldn't be defined in the first place and the data inside the for loop should be thrown away. Atleast that was always my understanding for now and that's probably also why ruff complained. 
Thanks for the report, I'm gonna dig deeper into that :)

**Comment by fpreynaud** [comment]
If that can help you, I'm using the terminology used by Windows, where (for example) HKEY_CLASSES_ROOT\ms-msime-imjpdct is the key, EditFlags is the value, and 0x00200000 is the data:

image

But sometimes the same can be referred as HKEY_CLASSES_ROOT\ms-msime-imjpdct\EditFlags as being the key, and 0x00200000 the value, without any mention of "data".

reg_query_value  accommodates for the two cases by saying: if the argument valueName is not None, we're in the first case (key, value, and data), otherwise we're in the second one (just key and value). Hence the if..else at the end.

Makes me realize I really need to comment this part of the code :laughing:

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Review by fpreynaud — COMMENTED** [review]
There's  a little problem on line 591, it should be `get_value(subkey_handle)[2]` instead of `get_value(subkey_handle)[3]`, because get_value only returns 3 values, not 4.

The module is working fine for now as the `if` is actually never entered, but it will throw an IndexError if that ever happens.

**Pull request merged**
