### PR TITLE
[ssh] Improvement

### PR DESCRIPTION
**Pull request by XiaoliChan**
- Rewrite SSH protocol
- Bring up Linux sudo check and Windows admin check

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
I'll check this out and give some feedback.

**Comment by XiaoliChan** [comment]
> 

Yes!

**Comment by XiaoliChan** [comment]
> I'll check this out and give some feedback.
> 
> @XiaoliChan are all changes done for this PR?

Yes !

**Comment by Marshall-Hallenbeck** [comment]
@XiaoliChan which OSes and versions did you test this against, and what sort of user privs (sudo no password, etc)

**Comment by XiaoliChan** [comment]
> @XiaoliChan which OSes and versions did you test this against, and what sort of user privs (sudo no password, etc)

For linux, I test with openwrt, debian, Kali Linux
For windows, I test with server 2109

**Pull request closed without merging**
