### PR TITLE
Revert #190 to enable null-auth without explicit specification

### PR DESCRIPTION
**Pull request by NeffIsBack**
PR to test if #207 is fixed with empty string auth (null auth)

### CODE REVIEW

**Comment by mpgn** [comment]
to be tested but it should work ok

**Comment by NeffIsBack** [comment]
Hmm that will always show the null auth tho. A lot of unnecessary output when you do `nxc smb <ip>/24 --shares`.
I would vote for just leaving it as it is and wait until that error occurs the next time. Then i can debug it properly, i really don't know how this should have happened (refering to the index out of bounds)

**Comment by mpgn** [comment]
Show me a screenshot of the output you see because I don't understand what you mean

**Comment by mpgn** [comment]
If you don't want any output if no -u -p then this pr should not be merged

**Comment by NeffIsBack** [comment]
image
That one is what i meant. That was the error you are aiming to fix right?

**Comment by NeffIsBack** [comment]
> If you don't want any output if no -u -p then this pr should not be merged

Yeah i just would like to roll it back to how it was all that time.

**Comment by mpgn** [comment]
Then merge the pr 🙂

**Comment by Marshall-Hallenbeck** [comment]
Just tested, gen relay works on this PR

**Review by mpgn — APPROVED** [review]

**Pull request merged**
