### PR TITLE
Several LDAP improvements

### PR DESCRIPTION
**Pull request by NeffIsBack**
## Fixing displaying wrong domain from host when manually specifying the domain. (see Screenshots below)
Now there are two attributes to differentiate between the host domain (self.targetDomain) and the domain we authenticate against (self.domain)
This is now fixed for all applicable protocols as you can see in the screenshots below.

## Connecting to ldap without explicitly specifying a domain does work and is now allowed:
image

### CODE REVIEW

**Comment by NeffIsBack** [comment]
@mpgn fixed for ldap
image

**Comment by NeffIsBack** [comment]
Now fixed for SMB as well
image

**Comment by NeffIsBack** [comment]
TBD: The SMB enumeration is also done in several other protocols. We should probably extract it into one function so it is fixed everywhere.

**Comment by mpgn** [comment]
👍

**Comment by Marshall-Hallenbeck** [comment]
@NeffIsBack is this still a draft, or can we get it done for v1.2?

**Comment by NeffIsBack** [comment]
I will try to get it done soon. But I think it's not that important, first I want to get the other PRs reviewed and merged

**Comment by NeffIsBack** [comment]
Fixed for mssql
image

**Comment by NeffIsBack** [comment]
Fixed for winrm, before and after:
image

**Comment by NeffIsBack** [comment]
Fixed for wmi, before and after:
image

**Review by mpgn — APPROVED** [review]

**Pull request merged**
