### PR TITLE
Add ascii art to cli

### PR DESCRIPTION
**Pull request by NeffIsBack**
Thanks to @bongobongoland here is a nice ascii art for the cli

### CODE REVIEW

**Review by Marshall-Hallenbeck — APPROVED** [review]

**Comment by bongobongoland** [comment]
what happened to the bite marks? :)

**Comment by NeffIsBack** [comment]
Oh lol I didn't knew what they are so I removed them

**Comment by bongobongoland** [comment]
It took me quite some time to arrange them. Every bite mark was unique :)

**Comment by XiaoliChan** [comment]
Really cool logo!

**Review by zblurx — APPROVED** [review]

**Pull request merged**
