### PR TITLE
[LDAP] Improvement (Reopen)

### PR DESCRIPTION
**Pull request by XiaoliChan**
Changelog:
- Get ntlm info via ldap connection (no more SMB needed)
- Remove SMB stuff
- Add `--ldap-timeout`
- Add `gc`

image

_`This PR is base on #196`_

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Conflicts need to be resolved before we can merge in the main branch and get the branch into a reviewable state :)

**Comment by XiaoliChan** [comment]
@NeffIsBack Sorry for the late response, the `ldaps` with timeout current is buggy, I will find a solution until I fix it.

**Comment by NeffIsBack** [comment]
@XiaoliChan no worries, just marked the PR so i know its not ready for a review. Take your time!

**Comment by XiaoliChan** [comment]
I‘m trying to figure out how to implement `timeout` in impacket ldap

**Comment by mpgn** [comment]
nice PR, working like a charm on my side ! Maybe more testing need to be done

before



after:



image

**Comment by mpgn** [comment]
i will do more testing on another lab later

**Comment by mpgn** [comment]
Trust relation ✅ 
image

**Comment by mpgn** [comment]
Using your PR i've decided to make another one based on your work but without the breaking part (aka keeping the original code as much as possible and avoid any variable naming)

Closing this one ! thanks @XiaoliChan as always !

**Pull request closed without merging**
