### PR TITLE
Added --dns-tcp and --dns-timeout to the ldap protocol when using --bloodhound

### PR DESCRIPTION
**Pull request by Fabrizzio53**
First time making a pr here so don't know If I need to do something else, I just added two options that are part of bloodhound-python, which is --dns-tcp and --dns-timeout, this help a lot since I could not use netexec bloodhound option when using a proxychains for example.

netexec_with_dns_tcp

### CODE REVIEW

**Review by mpgn — APPROVED** [review]

**Comment by Marshall-Hallenbeck** [comment]
I think this is redundant with #321, since I made these top level options.

**Comment by NeffIsBack** [comment]
That was my thought as well, but we should still pass the new options down to bloodhound.

@Fabrizzio53 thanks for the PR! Can you update the bloodhound parameters to use the new `--dns-server`/`--dns-tcp`... options?

**Comment by Fabrizzio53** [comment]
I changed all the proto_args.py file inside each protocol to remove errors when calling ldap and bloodhound, changed the paratemers at the AD() on bloodhound to use the new --dns-tcp and --dns-timeout top level options and removed the -ns option ob bloodhound to use the new --dns-server.

The first command use the tcp and works, the second one don't and fails

ok_error

zip_file

But for some reason smb is not showing now.

image

**Comment by Fabrizzio53** [comment]
Fixed, changed the proto_args from ssh to smb, now I changed to the correct one

**Comment by Marshall-Hallenbeck** [comment]
@Fabrizzio53 this is going to conflict with #321. Can you branch off that branch instead of main and make the changes?

**Comment by Fabrizzio53** [comment]
Just to be sure I create a pr to this branch? Pennyw0rth/NetExec:marshall-options-fix

**Comment by NeffIsBack** [comment]
Branching of means you create the branch when you are inside another branch, therefore `marshall-options-fix`. That new branch will than have all commits from the source branch (`marshall-options-fix`) in there and no merge conflicts when the other branch merges.

In this case just wait until tomorrow, than the PR should be merged anyway :)

**Comment by Marshall-Hallenbeck** [comment]
@Fabrizzio53 #321 was merged so you should be able to branch from `main`.

**Pull request closed without merging**
