### PR TITLE
Improving execution speed and misc command execution improvements

### PR DESCRIPTION
**Pull request by NeffIsBack**
This PR aims at two things:
- Improving command execution speed with timings and by polling 1x/s instead of 2x/s
- Waiting for powershell execution as using `-X` will report an `STATUS_SHARING_VIOLATION` when the command hasn't finished yet

The latter will still have a timeout, but we tolerant 10 times more tries when we can detect, that the command is still executing with the `STATUS_SHARING_VIOLATION` error.

With adding a small timeout before polling the first time we can decrease normal execution time by 1.5s which makes it way more nice2use:
image

Examples for waiting for powershell execution with all exec-methods:
image
image
Vs  cmd , where we can't track the command execution:
image

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Fyi there are a few problems with smbexec/atexec because of malformed powershell requests, but i think (&hope) they are fixed with #296

**Comment by Marshall-Hallenbeck** [comment]
@NeffIsBack Do we really want it to attempt 100 times? Why don't we just increase it to 10 and halve the sleep? It will then check 10 times in 10 seconds rather than 5 times in 10 seconds, and that can be increased by the user if they want.

**Comment by NeffIsBack** [comment]
> @NeffIsBack Do we really want it to attempt 100 times? Why don't we just increase it to 10 and halve the sleep? It will then check 10 times in 10 seconds rather than 5 times in 10 seconds, and that can be increased by the user if they want.

I added that because the sharing violation should only trigger if the powershell command is still running. On normal execution or with av it will quit after the 100/10=10 times (10 seconds). Imo its worth waiting a little bit longer (100s to be exact) for the file when we know the command is still executing (give heavy powershell commands a bit more time to breath). 

In regards to the polling rate, 1request/s isn't that much in network communications imo. We do way more connection attempts sometimes and this will just make it more responsive for the overall usage

**Comment by Marshall-Hallenbeck** [comment]
Oh I see the difference now - one is still in use (still writing?) and the other is "hasn't been created" (potentially failed).

100s might be a bit long, but I can definitely see wanting to wait longer for the command to write instead of just failing out when it's actually working.

**Review by Marshall-Hallenbeck — APPROVED** [review]

**Review by mpgn — APPROVED** [review]

**Pull request merged**
