### PR TITLE
Fix windows and encoding stuff

### PR DESCRIPTION
**Pull request by NeffIsBack**
This PR
- adds the new imports needed for the windows binary
- Fixes encoding issues such as #174
- On my system it also fixes the issue mentioned in #436, but that should be reevaluated

Before we had wrongly encoded output and crashes in the log handler with non latin-1/cp1252 encodings:
image

This is now fixed:
image

### CODE REVIEW

**Review by mpgn — DISMISSED** [review]

**Comment by NeffIsBack** [comment]
God damn it. Glad when we finally drop python 3.8...

**Comment by mpgn** [comment]
Do it 😉

**Comment by NeffIsBack** [comment]
First things i will do after the release

**Comment by NeffIsBack** [comment]
Should work like that as well, but for completeness this should be reverted when we drop 3.8 support

**Review by mpgn — APPROVED** [review]

**Pull request merged**
