### PR TITLE
[winrm] say goodbye to SMB

### PR DESCRIPTION
**Pull request by XiaoliChan**
Finally, we don't need SMB to gather NTLM info

image

Reference:
- https://github.com/nopfor/ntlm_challenger/tree/master
- https://github.com/JKme/cube/blob/master/core/probemodule/winrm.go

### CODE REVIEW

**Comment by mpgn** [comment]
image

all good for me 🎉

**Review by mpgn — DISMISSED** [review]

**Comment by NeffIsBack** [comment]
One small detail, we need the correct version enumeration from impacket. Then we can merge

**Comment by NeffIsBack** [comment]
> The what ? ^^

The windows OS enumeration I added to impacket😁 We can just import the check from impacket so we get the proper OS output

**Comment by mpgn** [comment]
You can add it @NeffIsBack ?

**Comment by XiaoliChan** [comment]
Now the `os verison` is usng the `WIN_VERSIONS` data.

And I move the `ntlm_parser.py` into `helpers`, then after that, the MSSQL can also invoke the function (codeless).

**Review by NeffIsBack — APPROVED** [review]
LGTM 👍 
image

**Pull request merged**
