### PR TITLE
refactoring to fix InterfaceError of DB

### PR DESCRIPTION
**Pull request by dazzgt**
**Issue topic** #395 
**Summary**
When netexec find a lot of suitable target hosts it start too many calls to DB at once and because of nature of SQLite it leads to `InterfaceError`. The same can happen with much fewer hosts but get that timing is much harder.
This PR don't fix IndexError mentioned in issue topic because it require dirty hack in current realization.

@AkechiShiro you can try to test it.

### CODE REVIEW

**Comment by dazzgt** [comment]
Updated. Accidentally delete `reflect_tables` from mssql database.

**Comment by Marshall-Hallenbeck** [comment]
@dazzgt nice, thanks for this PR. Have you run the e2e tests against any hosts?

**Comment by dazzgt** [comment]
> @dazzgt nice, thanks for this PR. Have you run the e2e tests against any hosts?

I ran it against the same subnet where i found this bug. Also there some rdp, winrm, smb test hosts, so i tried to run this protocols too. All works perfectly fine

**Comment by NeffIsBack** [comment]
Thanks for the PR! 
Please also run Ruff against the code (install poetry -> ˋpoetry run python -m ruff check . --previewˋ)

**Comment by dazzgt** [comment]
@NeffIsBack fixed two ruff errors.

**Comment by dazzgt** [comment]
If this solution is not good, then i open to suggestion how to fix it more elegant)

**Comment by NeffIsBack** [comment]
> If this solution is not good, then i open to suggestion how to fix it more elegant)

Hi, I am currently on vacation so I am not reviewing PRs at the moment. There are also a lot of PRs still waiting for a review, but I will take a deeper look at this one when am back at home. 
At first glance it looks good though :)

**Comment by AkechiShiro** [comment]
I'm sorry I haven't been able to test this PR on my side, I'm lacking time to do so but I believe it's a good improvement

**Comment by NeffIsBack** [comment]
I will test the performance of this next week, if there isn't a drastic change we should be good to go

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Pull request merged**
