### PR TITLE
Update handlekatz.py pypykatz import

### PR DESCRIPTION
**Pull request by 3ldidi94**
Fix pypykatz import in handlekatz

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Hey thanks again for the bug fix PR!
Somehow i can't get handlekatz to dumpy the process, even when executing the binary manually on the system. Any idea why this is? No AV present
image

**Comment by 3ldidi94** [comment]
Hey ! No problem, I had an error while parsing my dump `pypykatz has no attribute parse_minidum_external` and I don't have this when I am using nanodump.

About your issue using handlekatz, I am using this module but not the handlekatz binary in order to dump the lsass process. I will try it on my side and let you know if I have the same issue

**Comment by NeffIsBack** [comment]
Well, doing a manual dump and parsing it still doesn't work for some reason, but atleast the pypykatz import is fixed with this PR
image

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Comment by 3ldidi94** [comment]
> Hey thanks again for the bug fix PR! Somehow i can't get handlekatz to dumpy the process, even when executing the binary manually on the system. Any idea why this is? No AV present image

Same issue for me : 
image

**Comment by 3ldidi94** [comment]
> Hey thanks again for the bug fix PR! Somehow i can't get handlekatz to dumpy the process, even when executing the binary manually on the system. Any idea why this is? No AV present image

I am not using handlkatz, I have adapted an other lsass dumper to make it work with the handlekatz module. Did you fill the variable `handlekatz_b64` in the `HandleKatz.h` file?

**Comment by NeffIsBack** [comment]
I didn't pack the file myself. @mpgn wrote the module, not sure what you need to fill in. Maybe we should just repackage the binary though

**Pull request merged**
