### PR TITLE
Adding module to retrieve network interfaces info

### PR DESCRIPTION
**Pull request by Sant0rryu**
Useful to find subnets and servers for pivoting

### CODE REVIEW

**Comment by Dfte** [comment]
Love that PR, it's gonne be super useful for network pivoting!!

**Comment by Sant0rryu** [comment]
@Marshall-Hallenbeck I ran ruff on interface.py and fixed two warnings. 

Yes, it might actually be nice to have the option `--interface` as a default part of NXC under the mapping/enumeration section.

**Comment by Dfte** [comment]
Love the idea as well!

**Comment by Marshall-Hallenbeck** [comment]
@Sant0rryu so this seems to overlap with the `get_netconnections`, but also as I just tried to test this, it doesn't seem to output anything. Can you confirm it's working as intended? Which Windows versions did you test against?

**Comment by NeffIsBack** [comment]
Same here:
image

Added a bit of logging and it looks like there is a problem with the registry querying:
image

**Comment by Dfte** [comment]
@Sant0rryu you have got news ?

**Comment by NeffIsBack** [comment]
Reworked the module to a working core functionality:
(My desktop is a bit messy due to the thousands of network adapters, vmstuff)
image

**Review by mpgn — APPROVED** [review]

**Pull request merged**
