### PR TITLE
Added new modules for mssql- namely enum_impersonate, enum_logins,, enum_links, exec_on_link, link_enable_xp, link_xpcmd

### PR DESCRIPTION
**Pull request by deathflamingo**

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Thanks for the PR! Finally the MSSQL protocol gets some love :)

**Review by mpgn — APPROVED** [review]

**Comment by NeffIsBack** [comment]
@deathflamingo do you got a twitter handle i could mention in a post?

**Comment by deathflamingo** [comment]
Hey, sorry no I don't have a Twitter handle

**Comment by NeffIsBack** [comment]
Hi, i will rename the `link_enable_xp` module to `link_enable_cmdshell` so that it has the same naming scheme as the new modul `enable_cmdshell` from https://github.com/Pennyw0rth/NetExec/pull/557/files

**Pull request merged**
