### PR TITLE
Update Github Build Actions for Releases

### PR DESCRIPTION
**Pull request by Marshall-Hallenbeck**

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
Looks like it all built!

https://github.com/Pennyw0rth/NetExec/actions/runs/6228635143/job/16905726104

**Comment by Marshall-Hallenbeck** [comment]
But the windows binary crashes at runtime. More testing needed.

**Comment by Marshall-Hallenbeck** [comment]
Build went through (https://github.com/Pennyw0rth/NetExec/actions/runs/6238351109) and @NeffIsBack and I both confirmed the native Windows exe runs for us.

@NeffIsBack should be good for your approval!

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Pull request merged**
