### PR TITLE
refactoring of the ssh module to separate auth check / cmd checks

### PR DESCRIPTION
**Pull request by nikaiw**

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Thanks fot the contribution! Fyi, i changed the target branch to main

**Comment by Marshall-Hallenbeck** [comment]
@nikaiw can you undo the black formatting? it's a ton of unnecessary changes.

**Comment by nikaiw** [comment]
should be better I hope

**Comment by mpgn** [comment]
Thanks for the work 🙂

**Comment by Marshall-Hallenbeck** [comment]
@nikaiw can you run Ruff and fix any issues? `poetry run python -m ruff check . --preview` (--fix will autofix anything it can)

**Comment by nikaiw** [comment]
@Marshall-Hallenbeck yes, done. Sry actually I did it previously but I guess not with the latest ruff version. It should be better now

**Comment by NeffIsBack** [comment]
@nikaiw it looks like this is based of the old dev branch and is therefore quite outdated. 
Could you either resolve the conflicts or reopen the PR with the new changes applied to the latest commits of the main branch?
image

**Comment by NeffIsBack** [comment]
Fyi: gonna close this PR in favour of #331

**Pull request closed without merging**
