### PR TITLE
Add New Ldap Flag --active-users

### PR DESCRIPTION
**Pull request by termanix**
New ldap flag --active-users listing active users on domain. In real life test i encountered so many deactive accounts and it's wasting time.

### CODE REVIEW

**Comment by termanix** [comment]
image

**Review by Marshall-Hallenbeck — APPROVED** [review]
Very nice! Tested and it works great.

**Comment by Marshall-Hallenbeck** [comment]
@termanix Looks like there's 1 Ruff error if you could fix that!

**Comment by termanix** [comment]
Fixed now. Thank you for feedback and thoughts ^^

**Review by Marshall-Hallenbeck — APPROVED** [review]

**Pull request merged**
