### PR TITLE
Fix testing and linting

### PR DESCRIPTION
**Pull request by NeffIsBack**
Now we build with every python version which we support on approval and lint on every push (pull_request was redundant)
Also the test runner will now test if the installation on the platform is able to load every protocol and module:
image

Note: As I tested a bit this probably should get squashed merged

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
Tests are failing because the few tests I created in `tests/test_smb_database.py` are quite old. Might want to just disable running those tests for now, until we can actually get a proper (non-e2e) functional testing.

**Comment by NeffIsBack** [comment]
Ah yeah i just wanted to have something that checks that installations are working on every platform and with every supported python version. Maybe just disable the `poetry run pytest` for now? If we want to test installations i will add caching as well

**Comment by Marshall-Hallenbeck** [comment]
Yeah, I would get rid of that part, and just do the install. Maybe run the binary with -h after, to make sure stuff loads?

**Comment by NeffIsBack** [comment]
Sounds good!

**Review by Marshall-Hallenbeck — APPROVED** [review]

**Pull request merged**
