### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by NeffIsBack**
Updated dependency specifications to reflect the newest packages we crucially need like the newest dploot version or asyauth. 
I also updated some minimum requirements of important packages to a version that is also used in the kali packaging version so we will definitely have the same version on main and on kali. See: https://github.com/Pennyw0rth/NetExec/issues/211#issuecomment-2053766376

See commit 992ddc82b4a1cefe0951791669dcd6736b6570e8 for the dependency updates, rest is formating.

The actual packages i upgraded are the following:
image

EDIT:
Added `msldap = "^0.5.10"` which was missing so far.
Related issue #274

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
Why does the diff show replacing the entire pyproject file?

**Comment by NeffIsBack** [comment]
I switched from CRLF back to LF as requested by @arszilla for packaging. Also matches the rest of the files now
https://github.com/Pennyw0rth/NetExec/pull/269/commits/bc4416d567a0ee43b0d26bccd9bedcc626210c4a

**Comment by Marshall-Hallenbeck** [comment]
Running tests

**Review by Marshall-Hallenbeck — APPROVED** [review]
LGTM

**Pull request merged**
