### PR TITLE
Revert "[nanodump] fix error with temporary path"

### PR DESCRIPTION
**Pull request by Marshall-Hallenbeck**
Reverts Pennyw0rth/NetExec#67

Accidentally merged into `main`, not `develop`

### CODE REVIEW

**Review by NeffIsBack — APPROVED** [review]
😄

**Comment by NeffIsBack** [comment]
We probably should protect the main branch from pull requested not issued by us

**Comment by Marshall-Hallenbeck** [comment]
Can we disable PRs into `main` from other people?

**Review by zblurx — APPROVED** [review]

**Comment by NeffIsBack** [comment]
Not sure how but probably yes. A hacky way would be to have a GitHub action which just checks the author of a PR and fails if the main branch is the target. Set that as required in the branch protection rule and we should be good to go

**Pull request merged**
