### PR TITLE
Change jitter option to throttle authentications

### PR DESCRIPTION
**Pull request by NeffIsBack**
As it was requested multiple times now (see #181), i changed the deprecated jitter function to randomly insert sleeps before authenticating. This way you can throttle authentications on a per-target basis.

Syntax: 

- `nxc --jitter 3 smb...` will do a random 0-3 seconds delay
- `nxc --jitter 2-5 smb...` will do a random 2-5 seconds delay
- `nxc --jitter 5-5 smb...` will do an exact delay of 5 seconds

image

### CODE REVIEW

**Review by mpgn — APPROVED** [review]

**Review by Marshall-Hallenbeck — CHANGES_REQUESTED** [review]
Can you add the jitter commands to the e2e tests?

**Comment by NeffIsBack** [comment]
Done

**Comment by Marshall-Hallenbeck** [comment]
Can you also add a `jitter 3-5` and `jitter 4-4` or something so all 3 use-cases are covered?

**Comment by NeffIsBack** [comment]
sure, done

**Review by Marshall-Hallenbeck — APPROVED** [review]
LGTM!

**Pull request merged**
