### PR TITLE
#281 - Multi-file put/get for smb

### PR DESCRIPTION
**Pull request by wumb0**
Pennyw0rth/NetExec#281

I did not test this :)
Can do folder put later if you want.

### CODE REVIEW

**Comment by Marshall-Hallenbeck** [comment]
Thanks for the PR man! I'll test and update this, the nargs will need to be changed at least, but I'll fix it up. Appreciate the initial work on it!

**Comment by wumb0** [comment]
Shouldn't need to change `nargs`
```
In [11]: ap = ArgumentParser()

In [12]: ap.add_argument("--put-file", nargs=2, action="append")
Out[12]: _AppendAction(option_strings=['--put-file'], dest='put_file', nargs=2, const=None, default=None, type=None, choices=None, required=False, help=None, metavar=None)

In [13]: ap.parse_args("--put-file asdf fdsa --put-file jkfjdkf hgfdgfd".split())
Out[13]: Namespace(put_file=[['asdf', 'fdsa'], ['jkfjdkf', 'hgfdgfd']])
```
Thought it seems like my `isinstance(list)` logic is invalid. i think i can remove it.

**Review by Marshall-Hallenbeck — APPROVED** [review]
LGTM!

I was originally thinking that you'd pass in pairs into a single --put-file/etc, which is why I figured the nargs would be changed, but this works better I think.

**Comment by NeffIsBack** [comment]
@wumb0 if you got the time feel free to add the changes to the wiki :) 

https://github.com/Pennyw0rth/NetExec-Wiki

**Review by NeffIsBack — APPROVED** [review]
LGTM

**Pull request merged**
