### PR TITLE
Update neo4j python driver

### PR DESCRIPTION
**Pull request by NeffIsBack**
Updated neo4j python driver as it should not contain the performance issues as in neo4j itself. Atleast working without any problems so far:
image

### CODE REVIEW

**Comment by mpgn** [comment]
Why not the latest version ?

**Comment by mpgn** [comment]
ok for me and even using the latest 5.18
image

**Comment by NeffIsBack** [comment]
> Why not the latest version ?

It is using 5.18 when you look at the lock file.

**Comment by mpgn** [comment]
ah yeah good catch ^^

**Review by mpgn — APPROVED** [review]

**Pull request merged**
